<?php

namespace Elton\TeacherBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TicketReasonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketReasonRepository extends EntityRepository
{
}
