<?php

namespace Elton\TeacherBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketRepository extends EntityRepository
{
    public function getOpenTicket()
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery(
            'SELECT t
             FROM EltonTeacherBundle:Ticket t
             WHERE t.isSolved = false');
        
        $result = $query->getResult();
        return $result;
    }
}
