<?php

namespace Elton\LessonBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    
    /**
     * Get categorys by level id.
     * @param int $levelId id of the level
     * @return array Array of categorys
     * 
     */
    public function getCategoryByLevelId($levelId)
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery(
            'SELECT c
             FROM EltonLessonBundle:Category c
             JOIN c.level l
             WHERE l.id = :levelid ');
        $query->setParameter('levelid', $levelId);

        $result = $query->getResult();
        
        return $result;
    }
    
    /**
     * Get categorys by level name.
     * @param string $levelName name of the level
     * @return array Array of categorys
     * 
     */
    public function getCategoryByLevelName($levelName)
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery(
            'SELECT c
             FROM EltonLessonBundle:Category c
             JOIN c.level l
             WHERE l.libelle = :levelName ');
        $query->setParameter('levelName', $levelName);

        $result = $query->getResult();
        
        return $result;
    }
    
    /**
     * Get category by name
     * @param string $name name of the category
     * @return array Array filled up with one category
     */
    public function getCategoryByName($name)
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery(
                'SELECT c
                 FROM EltonLessonBundle:Category c
                 WHERE c.libelle = :name');
        $query->setParameter('name', $name);
        $result = $query->getResult();
        
        return $result;
    }
}
