<?php

namespace Elton\LessonBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    
    /**
     * Get categorys by level id.
     * @param int $levelId id of the level
     * @return array Array of categorys
     * 
     */
    public function getCategoryByLevelId($levelId)
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery(
            'SELECT *
             FROM EltonLessonBundle:Category c
             JOIN c.level l
             WHERE l.id = :levelid ');
        $query->setParameter('levelid', $levelId);

        $result = $query->getResult();
        
        return $result;
    }
}
