<?php

namespace Elton\LessonBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CompetanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompetanceRepository extends EntityRepository
{
}
