<?php

namespace Elton\PaymentBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PCodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubscriptionRepository extends EntityRepository
{
    /**
     * Function that verify PCode correspondance with postalCode of the school
     * @param string $pcode code of the pcode     
     * @param string $codep postalCode of the school
     * @return bool
     */
    public function getSubscriptionByCode($code)
    {
        
        $em = $this->getEntityManager();
        $query = $em->createQuery(
                'Select s
                From EltonPaymentBundle:Subscription s
                Where s.orderID = ?1');
        $query->setParameter(1, $code);   
        $result = $query->getResult();
        
        return $result;
    }
}
