<?php

namespace Elton\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FileRepository extends EntityRepository
{
    /**
     * Function used to count the number of Files
     * @return array with one int
     */
    public function count()
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery(
            'SELECT count(f)
             FROM EltonCoreBundle:File f');

        $result = $query->getSingleResult();
        
        return $result;
    }
    
    /**
     * Function used to find files by the their extension
     * @param string $extension extension of the file (file->url)
     * @return array of File
     */
    public function getFilesByExtension($extension)
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery(
                'Select f
                From EltonCoreBundle:File f
                Where f.url = ?1');
        $query->setParameter(1, $extension);
        $result = $query->getResult();
        
        return $result;
    }
}
