<?php

namespace Elton\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * JumbotronRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JumbotronRepository extends EntityRepository
{
}
