imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: @EltonCoreBundle/Resources/config/admin.xml }
    - { resource: @EltonTeacherBundle/Resources/config/mailer.xml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']   
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        name: "%session_name%"
        handler_id:  ~
        save_path: %kernel.root_dir%/var/sessions
        cookie_lifetime: 86400
    fragments:       ~
    http_method_override: true
    

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        lessphp:
            file: %kernel.root_dir%/../vendor/oyejorge/less.php/lessc.inc.php
            apply_to: "\.less$"
        cssrewrite:
            apply_to: '\.(css|less)$'
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        mapping_types:
            enum: string    
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: smtp
    host: localhost
    

fos_user:
    db_driver: orm 
    firewall_name: main
    user_class: Elton\CoreBundle\Entity\User
    from_email:
        address:        elton@playbac.fr
        sender_name:    My Elton
    registration:
        confirmation:
            enabled: true
            template: EltonTeacherBundle:Registration:email.txt.twig
    service:
        user_manager: pugx_user_manager
            
sonata_block:
    default_contexts: [cms]
    blocks:
        # Enable the SonataAdminBundle block
        sonata.block.service.backoffice:
        sonata.admin.block.admin_list:
            contexts:   [admin]
            
sonata_admin:
    title: myElton
    templates:
    dashboard:
        blocks:
                -
                    position: left
                    type: sonata.admin.block.admin_list
                -
                    position: right
                    type: sonata.block.service.backoffice
        
pugx_multi_user:
  users:
    user_one:
        entity: 
          class: Elton\TeacherBundle\Entity\Teacher
#          factory: 
        registration:
          form: 
            type: Elton\TeacherBundle\Form\RegistrationFormType
            name: fos_user_registration_form
            validation_groups:  [Registration, Default]
          template: EltonTeacherBundle:Registration:register.form.html.twig
        profile:
          form:
            type: Elton\TeacherBundle\Form\ProfileFormType
            name: fos_user_profile_edit
            validation_groups:  [Profile, Default] 
    user_two:
        entity: 
          class: Elton\DivisionBundle\Entity\Division
#        profile:
#          form: 
#            type: Acme\UserBundle\Form\Type\ProfileUserTwoFormType



